//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tacs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tacs.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma opção.
        /// </summary>
        public static string GeralSelecioneOpcao {
            get {
                return ResourceManager.GetString("GeralSelecioneOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno.
        /// </summary>
        public static string TelaAddAlunoAluno {
            get {
                return ResourceManager.GetString("TelaAddAlunoAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É a alternativa correta para a questão?.
        /// </summary>
        public static string TelaAlternativaCorreta {
            get {
                return ResourceManager.GetString("TelaAlternativaCorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string TelaAlternativaDescricao {
            get {
                return ResourceManager.GetString("TelaAlternativaDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string TelaAssuntoTitulo {
            get {
                return ResourceManager.GetString("TelaAssuntoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string TelaCreateTipoUsuario {
            get {
                return ResourceManager.GetString("TelaCreateTipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da disciplina.
        /// </summary>
        public static string TelaDisciplinaNome {
            get {
                return ResourceManager.GetString("TelaDisciplinaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string TelaQuestaoDescricao {
            get {
                return ResourceManager.GetString("TelaQuestaoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerto Casual.
        /// </summary>
        public static string TelaQuestaoFatorAcertoCasual {
            get {
                return ResourceManager.GetString("TelaQuestaoFatorAcertoCasual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificuldade.
        /// </summary>
        public static string TelaQuestaoFatorDificuldade {
            get {
                return ResourceManager.GetString("TelaQuestaoFatorDificuldade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        public static string TelaQuestaoFatorInformação {
            get {
                return ResourceManager.GetString("TelaQuestaoFatorInformação", resourceCulture);
            }
        }
    }
}
